import { AppRegistry } from 'react-native';
import App from './App';
import Login from './Screen/Login';
import FormAdd from './Screen/FormAdd';
import FormUpdate from './Screen/FormUpdate';
import TabManager from './Screen/TabManager';
import Register from './Screen/Register';
import Account from './Screen/Account';
import UpImage from './Screen/UpImage';
AppRegistry.registerComponent('Projectlab3', () =>App );
